[package]
name = "des"
version = "0.1.0"
authors = ["Kristofers Solo <dev@kristofers.xyz>"]
edition = "2024"

[dependencies]

[dev-dependencies]
claims = "0.8"
rand = "0.9"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
