[workspace]
resolver = "2"
members = ["des-lib", "bit-wrap"]

[workspace.dependencies]
bit-wrap = { path = "bit-wrap" }
thiserror = "2"
claims = "0.8"
rand = "0.9"
rstest = "0.26"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
