[workspace]
resolver = "2"
members = ["des-lib"]

[workspace.dependencies]
claims = "0.8"
rand = "0.9"
rstest = "0.26"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
